name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-info:
    name: PR Information
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            contracts/**
            backend/**
            frontend/**

      - name: List changed files
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Check for breaking changes
        run: |
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "contracts/"; then
            echo "⚠️ Smart contract changes detected. Ensure backward compatibility!"
          fi

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_CHAIN_ID: 41338
          NEXT_PUBLIC_RPC_URL: https://testnet-rpc.attelyx.io
          NEXT_PUBLIC_API_URL: http://localhost:3001
          NEXT_PUBLIC_FACTORY_ADDRESS: "0x0000000000000000000000000000000000000000"
          NEXT_PUBLIC_EXPLORER_URL: https://testnet-explorer.attelyx.io

      - name: Analyze bundle
        uses: SamirPS/next-js-bundle-analyzer-action@v1
        with:
          app-dir: frontend

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install contract dependencies
        run: npm ci
        working-directory: ./contracts

      - name: Run contract tests with coverage
        run: npm run test
        working-directory: ./contracts

      - name: Comment PR with coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./contracts/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  conventional-commits:
    name: Check Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
        continue-on-error: true

  approve-suggestion:
    name: Auto-approve Dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
